### ISSUE TITLE
Great Project， Can you share the TC3_PPE trained weights?

### ISSUE THREAD

**Issue by Byronnar** [bensonbs/YOLOv5-ZoeDepth-ZST#1]
Error: FileNotFoundError: [Errno 2] No such file or directory: 'models/TC3_PPE.pt', I want to try, Thanks.

**Comment by bensonbs** [comment]
https://drive.google.com/file/d/1ETXHz8ydbpaexW7_ctFSgulVkM72wiCc/view?usp=sharing
